// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3LyUK7QIcTtwje7EAtzPqnLDFJ1MogU',
    appId: '1:504972990838:web:21198075df2f63d2c4c257',
    messagingSenderId: '504972990838',
    projectId: 'brainscape-1126c',
    authDomain: 'brainscape-1126c.firebaseapp.com',
    storageBucket: 'brainscape-1126c.firebasestorage.app',
    measurementId: 'G-W3VZP1WZ5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrsvQTRFoffkJRz_Ito9Jd_TCNzhvBCU',
    appId: '1:504972990838:android:b58c7217273e06a6c4c257',
    messagingSenderId: '504972990838',
    projectId: 'brainscape-1126c',
    storageBucket: 'brainscape-1126c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADR6nbdmXWt0PtOl7-1c4npBNXJkDd2cQ',
    appId: '1:504972990838:ios:402f2ebbd8f8fc63c4c257',
    messagingSenderId: '504972990838',
    projectId: 'brainscape-1126c',
    storageBucket: 'brainscape-1126c.firebasestorage.app',
    iosBundleId: 'com.example.brainscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADR6nbdmXWt0PtOl7-1c4npBNXJkDd2cQ',
    appId: '1:504972990838:ios:402f2ebbd8f8fc63c4c257',
    messagingSenderId: '504972990838',
    projectId: 'brainscape-1126c',
    storageBucket: 'brainscape-1126c.firebasestorage.app',
    iosBundleId: 'com.example.brainscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX3LyUK7QIcTtwje7EAtzPqnLDFJ1MogU',
    appId: '1:504972990838:web:f35edd815da736b9c4c257',
    messagingSenderId: '504972990838',
    projectId: 'brainscape-1126c',
    authDomain: 'brainscape-1126c.firebaseapp.com',
    storageBucket: 'brainscape-1126c.firebasestorage.app',
    measurementId: 'G-YYTJGYDR5N',
  );
}
